### ISSUE TITLE
Can't find speaker embeddings.

### ISSUE THREAD

**Issue by thomas-happify** [chujiezheng/CoMAE#1]
Hi there,

Amazing work where you include cognitive science into the model! 

I have 2 questions: 

1. I didn't find any speaker embedding in the code where [`src_additive_embeds`](https://github.com/chujiezheng/UniModel/blob/915f71356c0da6e205225b4247358b5efbce9909/framework/comae/comae.py#L196-L206) only includes word, positional, DA, and EM embeddings.

2. What's the intuition of doing DA/EM/CM classifications first? It looks very similar to an autoencoder since `inputs == outputs`. Or did I misunderstood?

Thanks!

**Comment by chujiezheng** [comment]
Thanks for your interest!

1. `src_additive_embeds` only contains DA and EM embeddings. The speaker embeddings are added through `token_type_ids`. You can see that I add the token_type_embeddings [`here`](https://github.com/chujiezheng/UniModel/blob/915f71356c0da6e205225b4247358b5efbce9909/modeling/gpt2.py#L317)
2. Sorry, I do not understand what you mean. I first use the last hidden state of the context to predict the DA/EM/CM adopted in the response, and then use the predicted factors to control the response generation.

**Comment by thomas-happify** [comment]
@chujiezheng 
Thanks for the reply! it's really helpful.

I misunderstood the 2nd question yesterday so we are good.
