### ISSUE TITLE
issues about train_vanilla.sh and gpt2 true model

### ISSUE THREAD

**Issue by joy8joy8** [chujiezheng/CoMAE#10]
hello,

really appreciate your work!!
I have two issues that bother me a lot! please help me!

1.  the new model link you provided, 'https://huggingface.co/facebook/gpt2', lead to a 404 error page.
2. following your readme command,
 `## Training Your Model
Run `bash RUN/comae/train_vanilla.sh` to train your model.`, 
I couldn't find the file 'train_vanilla.sh' anywhere, instead there was a train.sh file.

**issue 1 please look：**
![image](https://user-images.githubusercontent.com/43362998/173311675-d0a8e8ee-a964-4bb1-9233-61854d6a6107.png)
**issue 2 please look：**
![image](https://user-images.githubusercontent.com/43362998/173312317-2a3fc4b9-f491-467a-9ece-86fe106544aa.png)

![image](https://user-images.githubusercontent.com/43362998/173312026-a32f35e9-26a3-4f0b-9e0e-e0f48564a125.png)

**Comment by chujiezheng** [comment]
They are typos. Sorry for that. I have fixed them, and please check again.

**Comment by joy8joy8** [comment]
thanks a lot. let me try again.
