### ISSUE TITLE
couldn't find or generate added_tokens.json

### ISSUE THREAD

**Issue by joy8joy8** [chujiezheng/CoMAE#11]
HELLO , it's me again.
I retry your codes, and encountered these problems, could you take a look and maybe you can provide added_tokens.json,  special_tokens_map.json and tokenizer_config.json. 
thanks 

> 06/13/2022 17:21:09 - INFO - tokenization.tokenization_utils_base  -  Didn't find file ./GPT2-small/added_tokens.json. We won't load it.

> 06/13/2822 17:21:09 - INFO - tokenization.tokenization_utils_base -  Didn't find file ./GPT2-small/special_tokens_map.json. We won't load it.

> 06/13/2022 17:21:09 - INFO - tokenization.tokenization_utils_base -  Didn't find file ./GPT2-small/tokenizer_config.json. We won't load it.

> 06/13/2022 17:21:09 - INFO - utils.building_utils -  pad_token_id in toker is inconsistent with model

> 06/13/2022 17:21:09 - INFO - utils.building_utils -  sep_token_id in toker is inconsistent with model
![8c16bf93422418df812bf2768539d3e](https://user-images.githubusercontent.com/43362998/173325915-cf25a0f9-5749-4b20-bbbf-b1d1731950f1.jpg)

**Comment by chujiezheng** [comment]
GPT-2 does not require these files. I think you can ignore these warnings.
