### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by Bushramjad** [chujiezheng/CoMAE#12]
Hi, I am getting this authorization error while executing the prepare.py file that leads to file_utils.py in the utils folder. Is there some kind of private model? how can I fix this?

Hoping to get a reply soon!

![Screenshot 2022-09-04 225152](https://user-images.githubusercontent.com/80513387/188326884-6aa5ed3e-f3c0-47a9-9002-b7b5627cdf56.png)

**Comment by chujiezheng** [comment]
Do you use the relative path for "tokenizer_path" (e.g., "./GPT2-small") in `codes/CONFIG/comae/comae.json`?

**Comment by Bushramjad** [comment]
It's  "tokenizer_path": "./GPT2-small"

**Comment by Bushramjad** [comment]
Yes, it worked by setting the relative path. Thanks Alot!
