### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by xiao-ming-code** [chujiezheng/CoMAE#3]
所下载的数据集是根据reddit已经处理过的么？？
数据集一句use的话对应会有多种回复，这是通过什么进行对应？

**Comment by chujiezheng** [comment]
多句回复当做多个sample处理

**Comment by xiao-ming-code** [comment]
> 多句回复当做了多个样品处理

有交互脚本么

**Comment by chujiezheng** [comment]
没有。你可以参照 https://github.com/thu-coai/Emotional-Support-Conversation/blob/main/codes_zcj/interact.py 改一个

**Comment by xiao-ming-code** [comment]
> 多句回复当做了多个样品处理

您好，就是数据集中的er,in ex，是表示什么，是CM么，分类的类型有哪些

**Comment by chujiezheng** [comment]
是CM。对应论文中的ER/IP/EX。类型有0和1。
