### ISSUE TITLE
train步骤

### ISSUE THREAD

**Issue by xiao-ming-code** [chujiezheng/CoMAE#4]
![7~~O(0HS1YOJGRRZB254A5K](https://user-images.githubusercontent.com/73177290/127618850-7158a1f0-62f3-4189-b8ba-105a11eab820.png)
在执行训练步骤的时候出现了这个错误，都是安装README进行执行，能麻烦看看这个问题么

**Comment by chujiezheng** [comment]
是bug，已修复

**Comment by xiao-ming-code** [comment]
> 是bug，已修复
您好，我想问下训练步骤大概需要多久 ， 如果把local_rank设置不等于1，是进行分布式训练么
训练时间好长我的

**Comment by chujiezheng** [comment]
分布式的代码我不知道能不能work
单卡应该三个小时能跑完吧
