### ISSUE TITLE
infer

### ISSUE THREAD

**Issue by zzcceeyy** [chujiezheng/CoMAE#5]
您好，我想咨询以下两个问题，就是关于论文部分在源码的具体位置：
1.L = Lnll+LA +LC +L E, 
![1628477674(1)](https://user-images.githubusercontent.com/88641930/128657020-4d699175-eb5f-401e-9649-edcfe9b0a401.png)

2.使用上下文最后位置的隐藏状态，Hx = Hx[1]∈Rd，来分层预测目标响应的CM、DA和EM。

![1628477691(1)](https://user-images.githubusercontent.com/88641930/128657046-117f753b-98d9-4c91-9401-c838163460dc.png)

**Comment by chujiezheng** [comment]
1. https://github.com/chujiezheng/CoMAE/blob/f007f3b3f1865d78a0c41a463136718207779af5/codes/framework/comae/comae.py#L241
2. https://github.com/chujiezheng/CoMAE/blob/f007f3b3f1865d78a0c41a463136718207779af5/codes/framework/comae/comae.py#L77
3. https://github.com/chujiezheng/CoMAE/blob/f007f3b3f1865d78a0c41a463136718207779af5/codes/framework/comae/comae.py#L121
4. https://github.com/chujiezheng/CoMAE/blob/f007f3b3f1865d78a0c41a463136718207779af5/codes/framework/comae/comae.py#L153

**Comment by zzcceeyy** [comment]
我运行的设备是有gpu的，运行的时候执行是cpu，无法使用gpu，想问下您的cuda版本
