### ISSUE TITLE
file

### ISSUE THREAD

**Issue by zzcceeyy** [chujiezheng/CoMAE#8]
Hello, I would like to know how the file here is generated. If I want to use data sets in other languages to train the model, how can I get this file? Thank you very much！
 《If you would like to evaluate generated results with Embedding-based similarity, you can download my prepared embedding files from here.》How did you get the embedded files here

**Comment by chujiezheng** [comment]
Maybe you can study the codes in [this directory](https://github.com/chujiezheng/CoMAE/tree/main/codes/metric/word2vec). But I am sorry that the embedding files are generated a long time ago, so I do not clearly remember how I generated these files.
